typography_spectrum: 0.6721594533883035
color:
  brandStrength: 0.9101276469882578
  lightness: 0.7518764387350529
  saturation: 0.314537942642346
  rhythmicContrast: 0.17228341731242836
  brandColors:
    - '#63A69F'
    - '#F2E1AC'
    - '#F2836B'
    - '#F2594B'
    - '#CD2C24'
opengraph:
  type: MaryOklahomaThoma
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9c51ec88-87ca-43ef-bca1-d2d0cb876baf.jpg
  appId: 'https://www.facebook.com/MaryOklahomaThoma/'
layout_spectrum: 0.18828758620657027
author:
  name: Mary LHT
  email: mrsjetjr@yahoo.com
  url: 'https://Make-it-in-Oklahoma.blogspot.com'
logo: null
name: Mary Oklahoma Thoma
navigation:
  - name: My ART
    url: 'http://Make-it-in-Oklahoma.blogspot.com'
    type: external
title: Making Art in Oklahoma
description: Artists make ART every day!
