typography_spectrum: 0.018027592450380325
color:
  brandStrength: 0.05720755993388593
  lightness: 0.41472523380070925
  saturation: 0.3926055005285889
  rhythmicContrast: 0.5728101406712085
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
layout_spectrum: 0.5279606820549816
name: Mary Oklahoma Thoma
title: Making Art in Oklahoma
