typography_spectrum: 0.1791414322797209
color:
  brandStrength: 0.1091345006134361
  lightness: 0.6786821591667831
  saturation: 0.6380001502111554
  rhythmicContrast: 0.06040936172939837
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
opengraph:
  type: MaryOklahomaThoma
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9c51ec88-87ca-43ef-bca1-d2d0cb876baf.jpg
  appId: 'https://www.facebook.com/MaryOklahomaThoma/'
layout_spectrum: 0.9002924968954176
author:
  name: Mary L Hockett Thoma
  email: mrsjetjr@yahoo.com
  url: 'https://Make-it-in-Oklahoma.blogspot.com'
logo: null
name: Mary Oklahoma Thoma
navigation:
  - name: My ART
    url: 'http://Make-it-in-Oklahoma.blogspot.com'
    type: external
title: Making Art in Oklahoma
description: Artists make ART every day!
